### ISSUE TITLE
Realtime

### ISSUE THREAD

**Issue by anmolduainter** [anubhavparas/visual-odometry#1]
Hi What are the steps to make it realtime ?

**Comment by anubhavparas** [comment]
With realtime you mean the realtime camera feed or the time it takes to process the video frames?

**Comment by anmolduainter** [comment]
Realtime processing of video frames.

**Comment by anubhavparas** [comment]
Ideally, it will be same as that for a video sequence because you need two successive frames to find the rotation and translation of the camera and then plot the same.
